@startuml Manage Company (POST)

header Sample Online Job Fair Sequence Diagram
footer Page %page% of %lastpage%
title "Create Company (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:companies" as routerCompanies
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:companies" as controllersCompanies
participant "<<model>>\n:Company" as modelCompany
database "<<MongoDB>>\n:companies" as CompaniesDatabase

client->server ++:req.post('/companies')
server->routerCompanies ++:app.use('/companies',companies)
routerCompanies -> authMiddleware ++: CheckAdminToken()
authMiddleware -> controllersCompanies ++:createCompany()
controllersCompanies -> modelCompany ++:create(req.body)
modelCompany -> CompaniesDatabase ++: CompanySchema
CompaniesDatabase --> modelCompany --: company
controllersCompanies <-- modelCompany --: company
controllersCompanies->client --:response



@enduml
